version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_SSL_CACERTFILE=/keys/cacert.pem
      - RABBITMQ_SSL_CERTFILE=/keys/cert.pem
      - RABBITMQ_SSL_KEYFILE=/keys/private.key
      - RABBITMQ_SSL_VERIFY=verify_peer
      - RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=false
      - RABBITMQ_MANAGEMENT_SSL_CACERTFILE=/keys/cacert.pem
      - RABBITMQ_MANAGEMENT_SSL_CERTFILE=/keys/cert.pem
      - RABBITMQ_MANAGEMENT_SSL_KEYFILE=/keys/private.key
      - RABBITMQ_MANAGEMENT_SSL_VERIFY=verify_peer
      - RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT=false
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./cacert.pem:/keys/cacert.pem:ro
      - ./cert.pem:/keys/cert.pem:ro
      - ./private.key:/keys/private.key:ro

  redis:
    image: redis:6.2.1-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    ports:
      - "6378:6378"
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis:/data
      - ./cacert.pem:/data/keys/cacert.pem
      - ./cert.pem:/data/keys/cert.pem
      - ./private.key:/data/keys/private.key
