name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y make
          python -m pip install -U pip
          pip install .[dev,redis]
      - name: Lint with mypy
        run: |
          mypy chive
      - name: Lint with black
        run: |
          black chive --check --diff --color
      - name: Integration tests
        run: |
          make integration_tests
